[package]
name = "imewatcher"
version = "0.2.1"
edition = "2024"
build = "build.rs"
license = "GPL-3.0-only"

[dependencies]
hidapi = "2.6.4"
log = "0.4.29"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_UI_Input_Ime", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_Shell", "Win32_System_LibraryLoader", "Win32_Globalization", "Win32_System_Threading", "Win32_Graphics_Gdi", "Win32_System_Console", "Win32_UI_Accessibility", "Win32_UI_Controls", "Win32_System_SystemServices", "Win32_System_SystemInformation"] }
native-windows-gui = "1.0.13"
qmk-via-api = { version = "0.5.0", default-features = false }

[build-dependencies]
embed-resource = "3.0.2"
